name: Test and Publish
on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    services:
      valkey:
        image: valkey/valkey:8.1.3
        ports:
          - 6379:6379
        options: >-
          --name valkey-server
          --health-cmd "valkey-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test
        env:
          VALKEY_HOST: localhost
          VALKEY_PORT: 6379

      - name: Publish
        run: npm publish

